#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

# Check all required programs
# are available
_requirements() {
  _check_cmd \
    'ffmpeg'
}

# shellcheck disable=SC2034
_global_variables() {
  recording_date=""
  recording_format=""
  recording_method=""
  out_stdout=""
  out_file=""
  audio_record=""
  bit_rate=""
  buffer_length=""
  recording_length=""
  encoding_delay=""
  scale_factor=""
  color=""
  quiet=""
}

_ffmpeg_options_load() {
  local \
    ffmpeg_options
  ffmpeg_options="${HOME}/.config/media-tools/ffmpeg_options"
  [ -e "${ffmpeg_options}" ] && \
    source \
      "${ffmpeg_options}" || \
  true
}

_encode() {
  local \
    _in="${1}" \
    _out="${2}" \
    _scale="${3}" \
    _audio="${4}" \
    _delay="${5}" \
    _mkmedia_opts=() \
    _ytencode_opts=() \
    _scaled \
    _audiovideo
  if [[ "${quiet}" != "y" ]]; then
    _mkmedia_opts+=(
      -v
    )
  fi
  _ytencode_opts+=(
    -m
      "fake"
  )
  sleep \
    "${_delay}"
  _msg_info \
    "encoding ${_in}"
  if [[ "${_scale}" != "1" ]]; then
    _msg_info \
      "scaling ${_in}"
    _scaled="$( \
      mktemp).mp4"
    vidscale \
      "${_in}" \
      "${_scaled}" \
      "${_scale}"
    rm \
      "${_in}"
    _in="${_scaled}"
  fi
  if [[ "${_audio}" != "" ]]; then
    _audiovideo="$( \
      mktemp).mp4"
    mkmedia \
      "${_mkmedia_opts[@]}" \
      "${_audiovideo}" \
      "${_audio}" \
      "${_in}"
    rm \
      "${_in}"
    _in="${_audiovideo}"
  fi
  ytencode \
    "${_ytencode_opts[@]}" \
    "${_in}" \
    "${_out}"
  rm \
    "${_in}"
}

_method_auto_detect() {
  if [[ "$(uname -o)" == "Android" ]]; then
    echo \
      'root'
  fi
}

_audio_auto_detect() {
  if [[ "$(uname -o)" == "Android" ]]; then
    _audiorecord_opts+=(
      -m
        'termux'
    )
  fi
  _audiorecord_opts+=(
    -k
      "${_buffer}"
    -l
      "${_buffer}"
  )
  _audio="true"
}

_root_screenrecord(){
  _screenrecord="/system/bin/screenrecord"
  _screenrecord_opts+=(
    --bit-rate
      "${_rate}"
  )
}

# Record screen
# $1: input video file
# $2: recording method (root)
# $2: delay seconds
# $3: output video file
_record() {
  local \
    _format="${1}" \
    _method="${2}" \
    _audio="${3}" \
    _rate="${4}" \
    _buffer="${5}" \
    _length="${6}" \
    _scale="${7}" \
    _delay="${8}" \
    _out=(
      "${9}"
    ) \
    _screenrecord_opts=() \
    _screenrecord \
    _audiorecord_opts=() \
    _audio_file \
    _tmp_dir \
    _tmp \
    _chunks \
    _i=0 \
    _vids=()
  if [[ "${_method}" == "auto" ]]; then
    _method="$( \
      _method_auto_detect)"
  fi
  if [[ "${_audio}" == "auto" ]]; then
    if [[ "${quiet}" != "y" ]]; then
      _audiorecord_opts+=(
        -v
      )
    fi
    _audio_auto_detect
  fi
  "_${_method}_screenrecord"
  _tmp_dir="$( \
    mktemp \
      -d)"
  _msg_info \
    "out: ${_out[*]}"
  if [[ "${_out[*]}" == "" ]] || \
     [[ "$(_get \
             "out" \
	     "stdout")" == "y" ]]; then
    _out+=(
      -
    )
  fi
  _chunks="$(( \
    _length / _buffer ))"
  while \
    (( _i < _chunks )); do
    _audio_file=""
    if [[ "${_audio}" == "true" ]]; then
      _audio_file="${_tmp_dir}/${_i}.opus"
      _run \
        "audiorecord_${_i}" \
        "0" \
        "async" \
        "audiorecord" \
          "${_audiorecord_opts[@]}" \
          "${_audio_file}" || \
	true
    fi
    _run \
      "record_${_i}" \
      "${_buffer}" \
      "sync" \
      "${_screenrecord}" \
        "${_screenrecord_opts[@]}" \
        "${_tmp_dir}/${_i}.hq.mp4" || \
      true
    _run \
      "encode_${_i}" \
      "0" \
      "async" \
      _encode \
        "${_tmp_dir}/${_i}.hq.mp4" \
        "${_tmp_dir}/${_i}.${_format}" \
	"${_scale}" \
        "${_audio_file}" \
	"${_delay}" || \
      true
    _vids+=(
      "${_tmp_dir}/${_i}.${_format}"
    )
    _i="$(( \
      _i + 1))"
  done
  _i=0
  while \
    (( _i < _chunks )); do
    wait \
      "$( \
        _get_pid \
	"encode_${_i}")"
    _i="$(( \
      _i + 1))"
  done 
  sleep \
    "$(( \
      _delay + 2))"
  vidcat \
    "${_out}" \
    "${_vids[@]}"
}

# Set defaults and, if present, overrides
# from program command line option parameters
_set_overrides() {
  _set_override \
    "audio" \
    "record" \
    "auto"
  _set_override \
    "recording" \
    "format" \
    "mp4"
  _set_override \
    "recording" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "recording" \
    "method" \
    "auto"
  _set_override \
    "out" \
    "file" \
    "$( \
      realpath \
        "recording_$( \
	  _get \
            "recording" \
	    "date").$(_get \
                        "recording" \
		        "format")")"
  _set_override \
    "bit" \
    "rate" \
    "16000000" # 16 Mb?
  _set_override \
    "buffer" \
    "length" \
    "60" # 60 seconds
  _set_override \
    "recording" \
    "length" \
    "120" # "$(( 24 * 60 * 60 ))" # 24 hours
  _set_override \
    "scale" \
    "factor" \
    "1"
  _set_override \
    "out" \
    "stdout" \
    "n"
  _set_override \
    "encoding" \
    "delay" \
    "20"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "           Recording date:   $(_get "recording" "date")"
  _msg_info "         Recording format:   $(_get "recording" "format")"
  _msg_info "             Audio record:   $(_get "audio" "record")"
  _msg_info "         Recording method:   $(_get "recording" "method")"
  _msg_info "                 Bit rate:   $(_get "bit" "rate")"
  _msg_info "            Buffer length:   $(_get "buffer" "length")"
  _msg_info "           Encoding delay:   $(_get "encoding" "delay")"
  _msg_info "         Recording length:   $(_get "recording" "length")"
  _msg_info "              Output file:   $(_get "out" "file")"
}


# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Record

Usage:
  $(_get "app" "name")
    [options]
    (<out_file>)
  options:
     -f                   Recording format
                          Default: $(_get "recording" "format")
     -m                   Recording method
                          Default: $(_get "recording" "method")
     -a                   Whether to record audio from the microphone.
                          Default: $(_get "audio" "record").
     -b                   Video bitrate.
                          Default: $(_get "bit" "rate").
     -k                   Encoding buffer length.
                          Default: $(_get "buffer" "length").
     -l                   Length of the recording.
                          Default: $(_get "recording" "length").
     -r                   Scale factor.
                          Default: $(_get "scale" "factor").
     -s                   Output to stdout.
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
_requirements
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'f:a:b:k:l:r:scvh?' \
    arg; do
  case \
    "${arg}" in
    f) override_recording_format="${OPTARG}" ;;
    m) override_recording_method="${OPTARG}" ;;
    a) override_audio_record="${OPTARG}" ;;
    b) override_bit_rate="${OPTARG}" ;;
    k) override_buffer_length="${OPTARG}" ;;
    l) override_recording_length="${OPTARG}" ;;
    r) override_scale_factor="${OPTARG}" ;;
    s) override_out_stdout="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
(( $# == 1 )) && \
  out_file="${1}"
_set_overrides
_config_user_init \
  "media-tools"
_show_config
_record \
  "${recording_format}" \
  "${recording_method}" \
  "${audio_record}" \
  "${bit_rate}" \
  "${buffer_length}" \
  "${recording_length}" \
  "${scale_factor}" \
  "${encoding_delay}" \
  "${out_file}"
